language: python

python:
    - "2.7"
    - "3.6"

cache:
    directories:
        - $HOME/.cache/pip

install:
    - pip3 install -r requirements.txt
    - pip install -r requirements.txt

script:
    - make test
